desktop:
  [
    "packages/desktop/*",
    "packages/desktop/**/*",
    "!packages/mobile/*",
    "!packages/mobile/**/*",
    "!packages/electron/*",
    "!packages/electron/**/*",
  ]
mobile:
  [
    "packages/mobile/*",
    "packages/mobile/**/*",
    "!packages/desktop/*",
    "!packages/desktop/**/*",
    "!packages/electron/*",
    "!packages/electron/**/*",
  ]
