desktop:
  - any: ["packages/desktop/**/*"]
    all: ["!packages/mobile/**/*", "!packages/electron/**/*"]

mobile:
  - any: ["packages/mobile/**/*"]
    all: ["!packages/desktop/**/*", "!packages/electron/**/*"]
