desktop:
  - all: ["packages/desktop/**/*"]
    any: ["!packages/mobile/**/*", "!packages/electron/**/*"]

mobile:
  - all: ["packages/mobile/**/*"]
    any: ["!packages/desktop/**/*", "!packages/electron/**/*"]
