desktop:
  - all: ["!packages/electron/**/*"]
  - all: ["!packages/mobile/**/*"]
  - all: ["!packages/electron/**/*", "!packages/mobile/**/*"]
mobile:
  - all: ["!packages/electron/**/*"]
  - all: ["!packages/desktop/**/*"]
  - all: ["!packages/electron/**/*", "!packages/desktop/**/*"]
# !a, !b
# !a
# !b
# +(a|b)
# +('!packages/mobile/**/*' | '!packages/electron/**/*')
# 데스크탑만 수정한 경우
# 일렉트론만 수정한 경우
# glob -> all(a || b)

# NO!
# 모바일만 수정한 경우                  !packages/mobile/**/*
# 일렉트론만 수정한 경우                 !packages/electron/**/*
# 특정 패키지만 수정한 경우에는 붙이면 안됨
#
